<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Andre.SoulsFormats"><HintPath>$(SmithboxRoot)/Andre.SoulsFormats.dll</HintPath></Reference>
    <Reference Include="Andre.Formats"><HintPath>$(SmithboxRoot)/Andre.Formats.dll</HintPath></Reference>
    <Reference Include="Andre.Core"><HintPath>$(SmithboxRoot)/Andre.Core.dll</HintPath></Reference>
    <Reference Include="Andre.IO"><HintPath>$(SmithboxRoot)/Andre.IO.dll</HintPath></Reference>
  </ItemGroup>
</Project>
